name: Build & Deploy TigrisSystem

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build release (bot-prod)
        run: |
          cargo build --release --bin bot-prod
          ls -l target/release/bot-prod

      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/release/bot-prod"
          target: "/tmp"
          overwrite: true

      - name: Switch release & restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            STAMP=$(date +%Y%m%d-%H%M%S)-$GITHUB_SHA
            install -d -m 0755 -o tigrissystem -g tigrissystem /opt/tigris-system/releases/$STAMP
            install -m 0755 -o tigrissystem -g tigrissystem /tmp/bot-prod /opt/tigris-system/releases/$STAMP/bot-prod
            ln -sfn /opt/tigris-system/releases/$STAMP /opt/tigris-system/current
            sudo /usr/bin/systemctl restart tigris_system.service
            sudo /usr/bin/systemctl --no-pager --full status tigris_system.service || true

